### ISSUE TITLE
is quic suitable for video streaming?

### ISSUE THREAD

**Issue by notedit** [devsisters/goquic#34]

**Comment by hodduc** [comment]
I think so, because Youtube uses QUIC as well as other Google services and having some benefits from QUIC.

https://groups.google.com/a/chromium.org/forum/#!searchin/proto-quic/youtube/proto-quic/BrMMwpI32KU/kGWBKe-NMQAJ https://groups.google.com/a/chromium.org/forum/#!searchin/proto-quic/youtube/proto-quic/_7EzqwFzu7I/05Ih3LaUx8UJ

I'm not sure that our implementation works well with video streaming. At least It is in my TODO list.

**Comment by notedit** [comment]
ok  i want to  wraite an  rtsp-server/client based quic.

will  look this later.

**Comment by pavan4** [comment]
@notedit did you go forward on quic based rtsp video streaming?
